---

- hosts: all
  become: true
  tasks:

  # - name: "Add EPEL repository"
  #   command: yum install -y epel-release
  #   when: ansible_distribution == "AlmaLinux"

  - name: "Update repository and installing apache and php package for AlmaLinux"
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

  - name: "Update repository and installing apache and php package for Ubuntu"
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


