---

- hosts: all
  become: true
  tasks:

  - name: "Installing apache package for AlmaLinux"
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "AlmaLinux"
  - name: "Installing apache package for Ubuntu"
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"


